### ISSUE TITLE
Reimplement the cart

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1061]
The cart should make a return so that users can do the following.

- [x] As a user I can add products under a project to the cart
- [x] As a user I can remove products from my cart
- [x] As a user I can see a list of products per project to see the impact to my budget should I order them all
- [x] As a user I can order all products in my cart for a project
- [x] As a user I can see the change in monthly costs should I add all products to a project
- [x] As a user I can see budget warnings should I add products which exceeds the project budget
- [x] As a user I must configure products before ordering

One catch is that products can require additional input from the user prior to ordering. So we must require that the products are configured prior to ordering.

- [ ] #1064 : Improve project budget reporting

**API**
- [x] #1062 : Allow multiple products to be ordered at once

**UX**
- [x] #1063 : Bring back the cart modal

\#TODO link sub-issues here

**Comment by chriskacerguis** [comment]
@AllenBW @AnkyrinRepeat Where are we with this?

**Comment by AnkyrinRepeat** [comment]
I believe all issues except possibly #1064 are resolved and were merged by https://github.com/boozallen/projectjellyfish/pull/1118.

I noticed it will stop you from exceeding the budget with the current order but doesn't check any other pending orders so I can't make a $5,000 order on a $4,000 budget, I can make two $3,000 orders.
